name: flutter_fire_app_template
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2

  # icon 生成
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.1

  # 状態管理
  flutter_riverpod: ^2.1.1
  rxdart:

  # freezed
  freezed_annotation: ^2.0.0
  json_annotation: ^4.4.0
  intl: ^0.17.0

  # Firebase
  firebase_core: ^2.1.0
  cloud_firestore: ^4.0.2
  firebase_analytics: ^10.0.2
  firebase_auth: ^4.0.2
  firebase_storage: ^11.0.2
  firebase_crashlytics: ^3.0.2
  firebase_dynamic_links: ^5.0.2
  firebase_messaging: ^14.0.2
  cloud_functions: ^4.0.2

  # Widget
  nil:
  extended_image: ^6.2.1
  auto_size_text: ^3.0.0

  # util
  simple_logger: ^1.9.0
  uuid:
  hashids2:
  package_info_plus: ^1.4.2

  # connect to device
  image_picker: ^0.8.5+3
  permission_handler: ^9.2.0

  # local storage
  shared_preferences: ^2.0.15

  # Route
  go_router: ^5.1.3

  # Validator
  form_validator: ^1.0.2

  # js
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

  # static analytics
  flutter_lints: ^2.0.0

  # gen
  flutter_gen_runner: ^4.2.1

  # freezed
  freezed: ^2.0.0
  json_serializable: ^6.1.4

  # import 整理
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
import_sorter:
  ignore_files:
    - lib/firebase_options.dart